version: '3.9'

services:

  glimpse-api:
    container_name: glimpse
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - gateway
      - s3
    depends_on:
      - gateway
      - auth
      - profiles
      - media

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_ADDRESS=gateway:3000
      - PROFILES_ADDRESS=profiles:8080
      - PROFILES_ENABLE_TLS=false
      - AUTH_ADDRESS=auth:8081
      - AUTH_ENABLE_TLS=false
    ports:
      - "3000:3000"
    depends_on:
      - profiles
      - auth
    restart: unless-stopped
    networks:
      - gateway

  auth:
    container_name: auth
    image: maxage/auth:master
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=glimpse
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=glimpse
      - POSTGRES_SSL_MODE=disable
      - API_ADDRESS=auth:8081
      - JWT_ACCESS_SECRET=secret
      - JWT_ACCESS_EXPIRATION=24h
      - JWT_REFRESH_SECRET=refresh_secret
      - JWT_REFRESH_EXPIRATION=720h
      - JWT_ISSUER=glimpse
      - METRICS_ADDRESS=auth:8087
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - postgres
      - gateway

  profiles:
    container_name: profiles
    image: maxage/profiles:master
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=glimpse
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=glimpse
      - POSTGRES_SSL_MODE=disable
      - API_ADDRESS=profiles:8080
      - MEDIA_ADDRESS=media:8082
      - METRICS_ADDRESS=profiles:8088
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - postgres
      - gateway

  media:
    container_name: media
    image: maxage/media:master
    environment:
      - API_ADDRESS=media:8082
      - S3_ADDRESS=minio:9000
      - S3_ACCESS_KEY=accesskey
      - S3_SECRET_KEY=secretkey
      - S3_BUCKET=media
      - S3_POLICY_FILE=./s3-policy.json
      - API_PUBLIC_HOST=localhost
      - METRICS_ADDRESS=media:8088
    ports:
      - "8082:8082"
    depends_on:
      - minio
    restart: unless-stopped
    networks:
      - s3
      - gateway

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: glimpse
      POSTGRES_USER: glimpse
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
      PGPORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres
      - .\migrations\tables.up.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - postgres

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: accesskey
      MINIO_ROOT_PASSWORD: secretkey
    command: server /data
    volumes:
      - minio-data:/data
    networks:
      - s3

volumes:
  minio-data:

networks:
  postgres:
    driver: bridge
  gateway:
    driver: bridge
  s3:
    driver: bridge