version: '3.9'

services:

  glimpse-api:
    container_name: glimpse
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - gateway
      - s3
    depends_on:
      - gateway
      - auth
      - profiles
      - media

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - profiles
      - auth
    restart: unless-stopped
    networks:
      - gateway

  auth:
    container_name: auth
    image: maxage/auth:master
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - postgres
      - gateway

  profiles:
    container_name: profiles
    image: maxage/profiles:master
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - postgres
      - gateway

  media:
    container_name: media
    image: maxage/media:master
    ports:
      - "8082:8082"
    depends_on:
      - minio
    restart: unless-stopped
    networks:
      - s3
      - gateway

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: glimpse
      POSTGRES_USER: glimpse
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
      PGPORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres
      - .\migrations\tables.up.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - postgres

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: accesskey
      MINIO_ROOT_PASSWORD: secretkey
    command: server /data
    volumes:
      - minio-data:/data
    networks:
      - s3

volumes:
  minio-data:

networks:
  postgres:
    driver: bridge
  gateway:
    driver: bridge
  s3:
    driver: bridge